// <auto-generated />
using System;
using ElRawda.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElRawda.Repository.Data.Migrations
{
    [DbContext(typeof(ELRawdaContext))]
    [Migration("20241112134512_Magzer")]
    partial class Magzer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElRawda.Core.Models.Cows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CowsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("cows");
                });

            modelBuilder.Entity("ElRawda.Core.Models.CowsPieces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CowId")
                        .HasColumnType("int");

                    b.Property<int>("MachId")
                        .HasColumnType("int");

                    b.Property<string>("PieceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PieceTybe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PieceWeight")
                        .HasColumnType("float");

                    b.Property<string>("dateOfSupply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateofExpiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CowId");

                    b.ToTable("cowsPieces");
                });

            modelBuilder.Entity("ElRawda.Core.Models.SlaughteredCow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CowsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfSlaughter")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachId")
                        .HasColumnType("int");

                    b.Property<double?>("Waste")
                        .HasColumnType("float");

                    b.Property<double>("WeightAtSlaughter")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("slaughteredCows");
                });

            modelBuilder.Entity("ElRawda.Core.Models.CowsPieces", b =>
                {
                    b.HasOne("ElRawda.Core.Models.SlaughteredCow", "Cow")
                        .WithMany()
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cow");
                });
#pragma warning restore 612, 618
        }
    }
}
